.TH sentplugin.properties "5" "10 Feb 2012" "sentplugin.properties" "Support Utilities Manual"
.SH NAME
sentplugin.properties \- NetIQ Sentinel Plugin configuration file for 
.BR supportconfig (8)
.
.SH DESCRIPTION
Supportconfig plugins add functionality to the supportconfig script. This plugin extends supportconfig's functionality to include information
about NetIQ Sentinel for use by Supportconfig's Sentinel plugin; this is not a plugin by itself.

.TP 18
SENTINSTALLBASE
The Sentinel base installation directory. The default is /.
.PD

.SH FILES
.I /usr/lib/supportconfig/plugins/sentplugin
.RS
The NetIQ Sentinel plugin
.RE
.I /usr/lib/supportconfig/plugins/sentplugin.properties
.RS
The NetIQ Sentinel plugin configuration file
.RE
.SH AUTHOR
Aaron Burgemeister <ab@novell.com>
.SH REPORTING BUGS
Pending
.SH SEE ALSO
.BR sentplugin (8)
.BR supportconfig (8)
.BR supportconfig.conf (5)

