.TH sentinel-plugin "8" "17 Jul 2010" "sentinel-plugin" "Support Utilities Manual"
.SH NAME
sentinel-plugin \- Novell Sentinel Plugin for 
.BR supportconfig (8)
.
.SH DESCRIPTION
SGathers troubleshooting information directly related to Sentinel. 
Supportconfig saves the plugin output as plugin-sentinel.txt.

.SH FILES
.I /opt/supportconfig/plugins/sentinel
.RS
The Sentinel plugin
.RE
.SH AUTHOR
Jason Record <jrecord@novell.com>
.SH REPORTING BUGS
Please submit bug fixes, comments or enhancement requests via: 
.B http://code.google.com/p/supportutils-plugin-sentinel/issues/list
.SH SEE ALSO
.BR supportconfig (8)
.BR supportconfig.conf (5)
