.TH sentplugin "8" "10 Feb 2012" "sentplugin" "Support Utilities Manual"
.SH NAME
sentplugin \- NetIQ Sentinel Plugin for 
.BR supportconfig (8)
.
.SH DESCRIPTION
Supportconfig plugins add functionality to the supportconfig script. This plugin extends supportconfig's functionality to include information
about NetIQ Sentinel. Supportconfig saves the plugin output as plugin-sentplugin.txt.

.SH FILES
.I /usr/lib/supportconfig/plugins/sentplugin
.RS
The NetIQ Sentinel plugin
.RE
.I /usr/lib/supportconfig/plugins/sentplugin.properties
.RS
The NetIQ Sentinel plugin configuration file
.RE
.SH AUTHOR
Aaron Burgemeister <ab@novell.com>
.SH REPORTING BUGS
http://code.google.com/p/supportutils-plugin-sentinel/issues/list
.SH SEE ALSO
.BR sentplugin.properties (5)
.BR supportconfig (8)
.BR supportconfig.conf (5)

