#!/bin/bash
###############################################################
# Name:        Sentinel Supportconfig Plugin
# Description: Gathers troubleshooting information directly 
#              related to Sentinel.
# License:     GPLv2
# Bugs:        http://en.opensuse.org/SC-Plugins#Reporting_Bugs
# Author:      Jason Record (jrecord@novell.com)
#              Aaron Burgemeister
###############################################################

SVER=1.03
LOG_LINES=500

. /opt/supportconfig/resources/scplugin.rc

section_header Sentinel Supportconfig Plugin, v${SVER}
section_header Sentinel Environment Variables for root
if ! env | grep ^ESEC_; then
	echo "ERROR: Sentinel environment variables not set"
	echo
fi

if [ -f /etc/init.d/sentinel ]; then
	section_header System Daemon Status
	chkconfig -l sentinel
	/etc/init.d/sentinel status

	section_header Network Port Status
	echo "# netstat -nap | egrep \"10012|10013|10014\""
	netstat -nap | egrep "10012|10013|10014"
fi

SHOME=$ESEC_HOME
if [ -n "$SHOME" ]; then
	section_header Sentinel Broker Connections
	echo "# $SHOME/bin/list_broker_connections.sh 127.0.0.1 10012"
	$SHOME/bin/list_broker_connections.sh 127.0.0.1 10012

	section_header "JAR File Version Compatibility"
	for SJAR in $(find $SHOME/lib -type f | grep jar$ | sort)
	do
		printf "%-60s - %s\n" "$SJAR" "$($SHOME/bin/versionreader.sh $SJAR)"
	done

	section_header Configuration Files
	for CLOG in $(find $SHOME/config -type f | sort)
	do
		cat_log $CLOG
	done 

	section_header Version History
	cat_log $SHOME/.version_history

	section_header Log Files: Last $LOG_LINES Lines
	for SLOG in $(find $SHOME/log -type f | grep 0.log$ | sort)
	do
		tail_log $SLOG
	done 

	section_header 3rd Party Log Files: Last $LOG_LINES Lines
	for TLOG in $(find $SHOME/3rdparty -type f | grep log$ | grep esec | sort)
	do
		tail_log $TLOG
	done 

	section_header Installation Logs: Last $LOG_LINES Lines
	for ILOG in $(find /opt/novell/sentinel6/install_log/ -maxdepth 1 -type f | sort)
	do
		tail_log $ILOG
	done

	section_header Cached Event Data Files
	echo "# find $SHOME/data/events -type f | xargs ls -l"
	find $SHOME/data/events -type f | xargs ls -l
fi
